### ISSUE TITLE
interactions with many same logical volume

### ISSUE THREAD

**Issue by palominogallo** [ClarkMcGrew/edep-sim#4] opened 2017-11-17 14:10 UTC
I have noticed, when we process some geometry using the density option and  including many physics volumes with same logical volume. EDEP-SIM locates the event in only one out of many physical volume.

**Comment by ClarkMcGrew** [comment] 2018-02-27 13:11
I can't reproduce this, and am closing it.  We can reopen it later if there's a still a problem

**Closed by ClarkMcGrew** 2018-02-27 13:11 UTC
